# Generated by Django 4.2.16 on 2024-12-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("skill_name", models.CharField(max_length=100)),
                ("country_name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
