# Generated by Django 4.2.16 on 2025-01-15 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0003_mymessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentJobState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Login", "Login"),
                            ("Searching Jobs", "Searching Jobs"),
                            ("Opening Company Link", "Opening Company Link"),
                            ("Submitting Application", "Submitting Application"),
                            ("Application Submitted", "Application Submitted"),
                            ("Error Occurred", "Error Occurred"),
                        ],
                        max_length=50,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("job_title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("is_successful", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automation.website",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
